// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0Th1kYaMvdb3-OgC540CTnRLt1ibPq4',
    appId: '1:944915015439:web:ffa2ccaba9703af480807a',
    messagingSenderId: '944915015439',
    projectId: 'coipen2151',
    authDomain: 'coipen2151.firebaseapp.com',
    databaseURL: 'https://coipen2151-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coipen2151.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj3UuQTRXrrfBb_Uchs4Bpj7cPGcWrVIg',
    appId: '1:944915015439:android:20a41f246d9fc91480807a',
    messagingSenderId: '944915015439',
    projectId: 'coipen2151',
    storageBucket: 'coipen2151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhWQ8l2arQC-rRMeTjS-d6t5LdMFLk58',
    appId: '1:944915015439:ios:e9a268a7cf20999d80807a',
    messagingSenderId: '944915015439',
    projectId: 'coipen2151',
    storageBucket: 'coipen2151.appspot.com',
    iosClientId: '944915015439-1tc320i0a86j4unf65oh233d112ss31s.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRhWQ8l2arQC-rRMeTjS-d6t5LdMFLk58',
    appId: '1:944915015439:ios:e9a268a7cf20999d80807a',
    messagingSenderId: '944915015439',
    projectId: 'coipen2151',
    storageBucket: 'coipen2151.appspot.com',
    iosClientId: '944915015439-1tc320i0a86j4unf65oh233d112ss31s.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
